name: Test
on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.version }}

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Gems
        run: bundle install

      - name: Execute tests
        run: bundle exec rspec
